# Generated by Django 5.1.6 on 2025-02-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
